name: 'Pre-Job'
description: 'Determines which jobs should run based on changed paths'
inputs:
  filters:
    description: 'Path filters as YAML string'
    required: true
  force-filters:
    description: 'Additional path filters that trigger force-run (e.g., workflow files)'
    required: false
    default: ''
  force-events:
    description: 'Events that should force all jobs to run (comma-separated)'
    required: false
    default: 'workflow_dispatch'
  force-branches:
    description: 'Branches that should force all jobs to run (comma-separated)'
    required: false
    default: ''
  exclude-branches:
    description: 'Branches to exclude from running (comma-separated)'
    required: false
    default: ''
  skip-force-logic:
    description: 'Skip the standard force logic (for special cases like weblate)'
    required: false
    default: 'false'

outputs:
  # Individual outputs that can be accessed directly
  should_run:
    description: 'Nested object with filter results (access via fromJSON(steps.pre-job.outputs.should_run).filter_name)'
    value: ${{ steps.generate-outputs.outputs.should_run }}

runs:
  using: 'composite'
  steps:
    - name: Convert filters to JSON
      id: convert-filters
      shell: python
      run: |
        import json
        import os
        import yaml

        # Get the filters input
        filters_yaml = """${{ inputs.filters }}"""

        try:
            # Parse YAML properly using the yaml library
            filters_dict = yaml.safe_load(filters_yaml)

            if not isinstance(filters_dict, dict):
                raise ValueError("Filters must be a YAML dictionary")

            if not filters_dict:
                raise ValueError("No valid filters found")

            # We only need the filter names (keys), not the actual path arrays
            filter_names = {name: [] for name in filters_dict.keys()}

            filters_json = json.dumps(filter_names)

            print("Converted filters to JSON:")
            print(filters_json)

            # Set GitHub Actions output
            with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                f.write(f"filters_json={filters_json}\n")

        except Exception as e:
            print(f"Error converting filters: {e}")
            exit(1)

    - name: Check conditions and determine if path filtering is needed
      id: check-conditions
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        force-events: ${{ inputs.force-events }}
        force-branches: ${{ inputs.force-branches }}
        exclude-branches: ${{ inputs.exclude-branches }}
        skip-force-logic: ${{ inputs.skip-force-logic }}
        filters-json: ${{ steps.convert-filters.outputs.filters_json }}
        script: |
          const script = require('./.github/actions/pre-job/check-conditions.js')
          script({ core, context })

    - name: Checkout code
      if: ${{ steps.check-conditions.outputs.needs_path_filtering == 'true' }}
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Check force paths
      if: ${{ steps.check-conditions.outputs.needs_path_filtering == 'true' && inputs.force-filters != '' }}
      id: force_paths
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        filters: |
          force-paths:
            ${{ inputs.force-filters }}

    - name: Check main paths
      if: ${{ steps.check-conditions.outputs.needs_path_filtering == 'true' && (inputs.force-filters == '' || steps.force_paths.outputs.force-paths != 'true') }}
      id: main_paths
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with:
        filters: ${{ inputs.filters }}

    - name: Generate final outputs
      id: generate-outputs
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        filters-json: ${{ steps.convert-filters.outputs.filters_json }}
        skip-force-logic: ${{ inputs.skip-force-logic }}
        force-triggered: ${{ steps.check-conditions.outputs.force_triggered }}
        should-skip: ${{ steps.check-conditions.outputs.should_skip }}
        needs-path-filtering: ${{ steps.check-conditions.outputs.needs_path_filtering }}
        force-path-results: ${{ toJSON(steps.force_paths.outputs) }}
        main-path-results: ${{ toJSON(steps.main_paths.outputs) }}
        script: |
          const script = require('./.github/actions/pre-job/generate-outputs.js')
          script({ core })
