name: Required Reviewers Check

on:
  pull_request_review:

jobs:
  check-member-review:
    uses: ./.github/workflows/check-team-approval.yml
    permissions:
      pull-requests: read
      contents: read
